### ISSUE TITLE
"Connection lost" sound, when connection is closed

### ISSUE THREAD

**Issue by danbruegge** [gonimo/gonimo#17]
Hi,

if i start a new connection to a baby and cut the connection later, i get a warning sound. This warning sound can only be pause/stopped on closing the android app in the taskmanager. This is quite annoying.

My wife and i both have this problem. We connect to an older Samsung Tablet. The problem occurs on multiple devices. Motorola X4 and Z Play, also on Samsung S10 and S10+.

Is this a known problem? Can we change something on our devices or is it an software problem?

Regards, Dan

**Comment by eskimor** [comment]
Hi @danbruegge!

Yeah this is a known problem, unfortunately. I am working on a fix (which isn't terribly easy, regrettably) - in the meantime you could use the web app, as there the bug is already fixed (was way easier here, as I am not suffering from Google restrictions).

I am sorry for the inconvenience and I am hoping to be able to deploy a fix soon!

**Comment by danbruegge** [comment]
Alright. Thanks for the answer. :) We'll will try it with the browser.

No need to apologize. Keep up the good work. :+1:
