### ISSUE TITLE
Gonimo shows loading screen.

### ISSUE THREAD

**Issue by danbruegge** [gonimo/gonimo#23]
Hi, gonimo is showing the loading screen without loading the app/browser.

![image](https://user-images.githubusercontent.com/1296438/121326301-b77dc780-c912-11eb-8185-e1f8ab9c67d6.png)

Is this the SSL problem again?

**Comment by eskimor** [comment]
Thank you! It should work again now.

**Comment by danbruegge** [comment]
Thank you. :+1: 

Is there a way that this could be automated? Maybe a cronjob to update the ssl cert?

**Comment by eskimor** [comment]
all there, it is just broken for some reason. :sweat:

**Comment by danbruegge** [comment]
Alright. Thanks for clarification. :)

**Comment by lovegandhi** [comment]
@eskimor this seems to be an issue today as well

**Comment by lovegandhi** [comment]
@eskimor please ignore my last comment, just noticed you put up an end of life notice in the wiki. Thanks for making this available to us all!

**Comment by eskimor** [comment]
I turned it off and on again - seems to be working now. Thanks for using Gonimo! Users like you are the reason I kept the project alive so long :-)

**Comment by danbruegge** [comment]
Can you recommend a good alternative?
And also, can you put the end of life info into the readme, so other user will see it faster?

Thanks for your great work. Will look into alternatives.

**Comment by eskimor** [comment]
Will do, I don't really know a good alternative when it comes to open source solutions, which was the reason I wrote this. For non OSS solutions, baby monitor 3g seems to be pretty decent.

**Comment by arkonbob** [comment]
Oh that is a shame - it's been perfect for us and has seen our 2.5 year old all the way through since she was born. Many thanks for all your hard work that you've shared with the community. As you say, there is really no comparable alternative out there.

I am now wondering if it would be reasonably straight-forward to self host, ideally as a docker image? I can do without the Android app (Chrome/Safari/Edge "Install site as app" do almost the same job). For myself I would prefer to drop any SSL/certification requirement as it would be only be accessible via the local LAN/VPN.

**Comment by eskimor** [comment]
Hi @arkonbob ! Glad Gonimo worked so well for you :-) For the self hosting, you can try building it yourself and I will gladly assist in the process. For TLS/SSL - you have to enable it unfortunately as otherwise webrtc will not work.

In any case, I do not intend to shut down the service for the time being - I just don't have resources maintaining it. So if occasional hickups (SSL issues and stuff) are ok for you, you will continue to be able to use the service for quite a while. Seeing that there is still some interest in the service, I might even find the time to track down the issue with those auto updates. In any case, if the service stops working - filing an issue to bring it to my attention works reasonably well - I will fix operational issues, if it does not lead to  a huge amount of work.

**Comment by arkonbob** [comment]
That's great to hear! I will probably look at self-hosting as a migration path for the future but I'm glad there's no urgency yet. Thanks again.

**Comment by danbruegge** [comment]
Hi, after every installation on our phones/tablets was broken one by one again, we decided to switch. Did some long search and at the end i'm happy with https://play.google.com/store/apps/details?id=com.arjonasoftware.babycam
The promise is that no data is sent to third party server. This is something I was looking for. :+1: 

@eskimor thanks for your good and hard work. The last 2 years, Gonimo was an awesome companion, and I'm a bit sad to drop it now. But as our kids evolve, the rest has too. :smile:

**Comment by eskimor** [comment]
Glad it was useful and very happy you found an alternative. :-)
